In [1]:
import pandas as pd
import numpy as np

In [51]:
hotels = pd.read_csv("datasets/hotel_bookings.csv")
hotels.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

Summary of Columns:
hotel: Name of hotel
is_canceled: Whether the booking was canceled (1) or kept (0)
lead_time: Number of days between booking date and arrival date
arrival_date_year: Year of arrival date
arrival_date_month: Month of arrival date
arrival_date_week_number: Week number of arrival date
arrival_date_day_of_month: Day of the month of arrival date
stays_in_weekend_nights: Number of weekend nights booked (Sat-Sun)
stay_in_week_nights: Number of weekday nights booked (Mon-Fri)
adults: Number of adults
children: Number of children
babies: Number of babies
meal: Type of meal booked (Undefined/SC, BB, HB, or FB)
country: Country of origin of the booker
market_segment: Market segment (TA - travel agent, TO - tour operators)
distribution_channel: Booking distribution channel (TA - travel agent, TO - tour operators)
is_repeated_guest: Is this a repeated guest (1) or not (0)
previous_cancellations: The number of previous bookings canceled by the customer
previous_bookings_not_canceled: The number of previous bookings not canceled by the customer
reserved_room_type: Room type reserved
assigned_room_type: Type of assigned room booked
booking_changes: Number of booking changes or modifications
deposit_type: Type of deposit to guarantee booking (No Deposit, Non Refund, or Refundable)
agent: ID of the travel agency that made the booking
company: ID of the company that made the booking
days_in_waiting_list: Number of days booking was waitlisted before confirmation
customer_type: The customer type of booking (Contract, Group, Transient, or Transient-party)
adr: The average daily rate (cost) of the booking
required_car_parking_spaces: Number of parking spaces requested by the customer
total_of_special_requests: Number of special requests by the customer
reservation_status: The last reservation status (Canceled, Check-Out, No-Show)
reservation_status_date: The date of the last reservation status

In [15]:
hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [25]:
# Number of cancellations
print(hotels["is_canceled"].value_counts(0))

# Percentage of cancellations
print(hotels["is_canceled"].value_counts(1))

is_canceled
0    75166
1    44224
Name: count, dtype: int64
is_canceled
0    0.629584
1    0.370416
Name: proportion, dtype: float64

In [27]:
# Reservation status count
print(hotels["reservation_status"].value_counts(0))

# Reservation status percentage
print(hotels["reservation_status"].value_counts(1))

reservation_status
Check-Out    75166
Canceled     43017
No-Show       1207
Name: count, dtype: int64
reservation_status
Check-Out    0.629584
Canceled     0.360307
No-Show      0.010110
Name: proportion, dtype: float64

In [31]:
cancellations_by_month = hotels.groupby('arrival_date_month')['is_canceled'].mean()
cancellations_by_month.sort_values()

arrival_date_month
January      0.304773
November     0.312334
March        0.321523
February     0.334160
December     0.349705
July         0.374536
August       0.377531
October      0.380466
September    0.391702
May          0.396658
April        0.407972
June         0.414572
Name: is_canceled, dtype: float64

In [39]:
# Visualise the non-numeric features
cat_columns = hotels.select_dtypes(include=["object", "category"]).columns
hotels[cat_columns].head()

,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
0,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
1,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out,2015-07-01
2,July,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out,2015-07-02
3,July,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out,2015-07-02
4,July,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-07-03

In [47]:
for col in cat_columns:
    # Counts
    print(f"{col.upper()} count: {hotels[col].value_counts(0)}")
    
    # Proportions
    print(f"{col.upper()} count: {hotels[col].value_counts(1)}")

ARRIVAL_DATE_MONTH count: arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64
ARRIVAL_DATE_MONTH count: arrival_date_month
August       0.116233
July         0.106047
May          0.098760
October      0.093475
April        0.092880
June         0.091624
September    0.088014
March        0.082034
February     0.067577
November     0.056906
December     0.056789
January      0.049661
Name: proportion, dtype: float64
MEAL count: meal
BB           92310
HB           14463
SC           10650
Undefined     1169
FB             798
Name: count, dtype: int64
MEAL count: meal
BB           0.773180
HB           0.121141
SC           0.089203
Undefined    0.009791
FB           0.006684
Name: proportion, dtype: float64
COUNTRY count: country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
DJI        1
BWA        1
HND        1
VGB        1
NAM        1
Name: count, Length: 177, dtype: int64
COUNTRY count: country
PRT    0.408656
GBR    0.102008
FRA    0.087593
ESP    0.072059
DEU    0.061286
         ...
DJI    0.000008
BWA    0.000008
HND    0.000008
VGB    0.000008
NAM    0.000008
Name: proportion, Length: 177, dtype: float64
MARKET_SEGMENT count: market_segment
Online TA        56477
Offline TA/TO    24219
Groups           19811
Direct           12606
Corporate         5295
Complementary      743
Aviation           237
Undefined            2
Name: count, dtype: int64
MARKET_SEGMENT count: market_segment
Online TA        0.473046
Offline TA/TO    0.202856
Groups           0.165935
Direct           0.105587
Corporate        0.044350
Complementary    0.006223
Aviation         0.001985
Undefined        0.000017
Name: proportion, dtype: float64
DISTRIBUTION_CHANNEL count: distribution_channel
TA/TO        97870
Direct       14645
Corporate     6677
GDS            193
Undefined        5
Name: count, dtype: int64
DISTRIBUTION_CHANNEL count: distribution_channel
TA/TO        0.819750
Direct       0.122665
Corporate    0.055926
GDS          0.001617
Undefined    0.000042
Name: proportion, dtype: float64
RESERVED_ROOM_TYPE count: reserved_room_type
A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: count, dtype: int64
RESERVED_ROOM_TYPE count: reserved_room_type
A    0.720278
D    0.160826
E    0.054737
F    0.024265
G    0.017539
B    0.009364
C    0.007806
H    0.005034
P    0.000101
L    0.000050
Name: proportion, dtype: float64
ASSIGNED_ROOM_TYPE count: assigned_room_type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64
ASSIGNED_ROOM_TYPE count: assigned_room_type
A    0.620261
D    0.212095
E    0.065382
F    0.031418
G    0.021384
C    0.019893
B    0.018117
H    0.005964
I    0.003040
K    0.002337
P    0.000101
L    0.000008
Name: proportion, dtype: float64
DEPOSIT_TYPE count: deposit_type
No Deposit    104641
Non Refund     14587
Refundable       162
Name: count, dtype: int64
DEPOSIT_TYPE count: deposit_type
No Deposit    0.876464
Non Refund    0.122179
Refundable    0.001357
Name: proportion, dtype: float64
CUSTOMER_TYPE count: customer_type
Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: count, dtype: int64
CUSTOMER_TYPE count: customer_type
Transient          0.750591
Transient-Party    0.210436
Contract           0.034140
Group              0.004833
Name: proportion, dtype: float64
RESERVATION_STATUS count: reservation_status
Check-Out    75166
Canceled     43017
No-Show       1207
Name: count, dtype: int64
RESERVATION_STATUS count: reservation_status
Check-Out    0.629584
Canceled     0.360307
No-Show      0.010110
Name: proportion, dtype: float64
RESERVATION_STATUS_DATE count: reservation_status_date
2015-10-21    1461
2015-07-06     805
2016-11-25     790
2015-01-01     763
2016-01-18     625
              ...
2015-02-27       1
2015-04-25       1
2015-03-11       1
2015-06-14       1
2015-02-12       1
Name: count, Length: 926, dtype: int64
RESERVATION_STATUS_DATE count: reservation_status_date
2015-10-21    0.012237
2015-07-06    0.006743
2016-11-25    0.006617
2015-01-01    0.006391
2016-01-18    0.005235
                ...
2015-02-27    0.000008
2015-04-25    0.000008
2015-03-11    0.000008
2015-06-14    0.000008
2015-02-12    0.000008
Name: proportion, Length: 926, dtype: float64

In [53]:
drop_columns = ['hotel','country', 'agent', 'company', 'reservation_status_date',
                'arrival_date_week_number', 'arrival_date_day_of_month', 'arrival_date_year']

hotels = hotels.drop(labels=drop_columns, axis=1)
print(hotels.columns)

Index(['is_canceled', 'lead_time', 'arrival_date_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status'],
      dtype='object')

In [57]:
hotels['meal'] = hotels['meal'].replace({
    'Undefined': 0,
    'SC': 0,
    'BB': 1,
    'HB': 2,
    'FB': 3
})

In [69]:
one_hot_columns = ['arrival_date_month', 'distribution_channel', 'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type', 'market_segment']

hotels = pd.get_dummies(hotels, columns=one_hot_columns, dtype=int)

hotels.head()
# print(hotels.columns)

Index(['is_canceled', 'lead_time', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests', 'reservation_status',
       'arrival_date_month_April', 'arrival_date_month_August',
       'arrival_date_month_December', 'arrival_date_month_February',
       'arrival_date_month_January', 'arrival_date_month_July',
       'arrival_date_month_June', 'arrival_date_month_March',
       'arrival_date_month_May', 'arrival_date_month_November',
       'arrival_date_month_October', 'arrival_date_month_September',
       'distribution_channel_Corporate', 'distribution_channel_Direct',
       'distribution_channel_GDS', 'distribution_channel_TA/TO',
       'distribution_channel_Undefined', 'reserved_room_type_A',
       'reserved_room_type_B', 'reserved_room_type_C', 'reserved_room_type_D',
       'reserved_room_type_E', 'reserved_room_type_F', 'reserved_room_type_G',
       'reserved_room_type_H', 'reserved_room_type_L', 'reserved_room_type_P',
       'assigned_room_type_A', 'assigned_room_type_B', 'assigned_room_type_C',
       'assigned_room_type_D', 'assigned_room_type_E', 'assigned_room_type_F',
       'assigned_room_type_G', 'assigned_room_type_H', 'assigned_room_type_I',
       'assigned_room_type_K', 'assigned_room_type_L', 'assigned_room_type_P',
       'deposit_type_No Deposit', 'deposit_type_Non Refund',
       'deposit_type_Refundable', 'customer_type_Contract',
       'customer_type_Group', 'customer_type_Transient',
       'customer_type_Transient-Party', 'market_segment_Aviation',
       'market_segment_Complementary', 'market_segment_Corporate',
       'market_segment_Direct', 'market_segment_Groups',
       'market_segment_Offline TA/TO', 'market_segment_Online TA',
       'market_segment_Undefined'],
      dtype='object')

In [73]:
print(hotels.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 71 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   is_canceled                     119390 non-null  int64
 1   lead_time                       119390 non-null  int64
 2   stays_in_weekend_nights         119390 non-null  int64
 3   stays_in_week_nights            119390 non-null  int64
 4   adults                          119390 non-null  int64
 5   children                        119386 non-null  float64
 6   babies                          119390 non-null  int64
 7   meal                            119390 non-null  int64
 8   is_repeated_guest               119390 non-null  int64
 9   previous_cancellations          119390 non-null  int64
 10  previous_bookings_not_canceled  119390 non-null  int64
 11  booking_changes                 119390 non-null  int64
 12  days_in_waiting_list            119390 non-null  int64
 13  adr                             119390 non-null  float64
 14  required_car_parking_spaces     119390 non-null  int64
 15  total_of_special_requests       119390 non-null  int64
 16  reservation_status              119390 non-null  object
 17  arrival_date_month_April        119390 non-null  int32
 18  arrival_date_month_August       119390 non-null  int32
 19  arrival_date_month_December     119390 non-null  int32
 20  arrival_date_month_February     119390 non-null  int32
 21  arrival_date_month_January      119390 non-null  int32
 22  arrival_date_month_July         119390 non-null  int32
 23  arrival_date_month_June         119390 non-null  int32
 24  arrival_date_month_March        119390 non-null  int32
 25  arrival_date_month_May          119390 non-null  int32
 26  arrival_date_month_November     119390 non-null  int32
 27  arrival_date_month_October      119390 non-null  int32
 28  arrival_date_month_September    119390 non-null  int32
 29  distribution_channel_Corporate  119390 non-null  int32
 30  distribution_channel_Direct     119390 non-null  int32
 31  distribution_channel_GDS        119390 non-null  int32
 32  distribution_channel_TA/TO      119390 non-null  int32
 33  distribution_channel_Undefined  119390 non-null  int32
 34  reserved_room_type_A            119390 non-null  int32
 35  reserved_room_type_B            119390 non-null  int32
 36  reserved_room_type_C            119390 non-null  int32
 37  reserved_room_type_D            119390 non-null  int32
 38  reserved_room_type_E            119390 non-null  int32
 39  reserved_room_type_F            119390 non-null  int32
 40  reserved_room_type_G            119390 non-null  int32
 41  reserved_room_type_H            119390 non-null  int32
 42  reserved_room_type_L            119390 non-null  int32
 43  reserved_room_type_P            119390 non-null  int32
 44  assigned_room_type_A            119390 non-null  int32
 45  assigned_room_type_B            119390 non-null  int32
 46  assigned_room_type_C            119390 non-null  int32
 47  assigned_room_type_D            119390 non-null  int32
 48  assigned_room_type_E            119390 non-null  int32
 49  assigned_room_type_F            119390 non-null  int32
 50  assigned_room_type_G            119390 non-null  int32
 51  assigned_room_type_H            119390 non-null  int32
 52  assigned_room_type_I            119390 non-null  int32
 53  assigned_room_type_K            119390 non-null  int32
 54  assigned_room_type_L            119390 non-null  int32
 55  assigned_room_type_P            119390 non-null  int32
 56  deposit_type_No Deposit         119390 non-null  int32
 57  deposit_type_Non Refund         119390 non-null  int32
 58  deposit_type_Refundable         119390 non-null  int32
 59  customer_type_Contract          119390 non-null  int32
 60  customer_type_Group             119390 non-null  int32
 61  customer_type_Transient         119390 non-null  int32
 62  customer_type_Transient-Party   119390 non-null  int32
 63  market_segment_Aviation         119390 non-null  int32
 64  market_segment_Complementary    119390 non-null  int32
 65  market_segment_Corporate        119390 non-null  int32
 66  market_segment_Direct           119390 non-null  int32
 67  market_segment_Groups           119390 non-null  int32
 68  market_segment_Offline TA/TO    119390 non-null  int32
 69  market_segment_Online TA        119390 non-null  int32
 70  market_segment_Undefined        119390 non-null  int32
dtypes: float64(2), int32(54), int64(14), object(1)
memory usage: 40.1+ MB
None

In [75]:
import torch
import torch.nn as nn
import torch.optim as optim

ModuleNotFoundError: No module named 'torch'